### ISSUE TITLE
browser_umd.connect is not a function ?

### ISSUE THREAD

**Issue by jhh78** [sveltejs/community#3]
I used sveltjs + sapper + mongoose.

Input to DB works without any problem, but an error is occurring.
please tell me how to solve it

`TypeError: browser_umd.connect is not a function
    at Object.addItem (mongo.js:9:28)
    at instance (index.svelte:5:8)
    at init$1 (index.mjs:1862:11)
    at new Routes (index.svelte:5:38)
    at Array.create_else_block (App.svelte:24:44)
    at Array.create_default_slot (App.svelte:21:12)
    at create_slot (index.mjs:69:29)
    at create_fragment$2 (Nav.svelte:2:20)
    at init$1 (index.mjs:1877:37)
    at new Layout (_layout.svelte:4:20)`

**Comment by skorphil** [comment]
Same eeror while trrying to deploy astro + mongoose on cloudflate pages. Any solution after a 2 years?
